# Change default shell
set -g default-shell /usr/bin/zsh

# enable 256 colors
set -g default-terminal "screen-256color"

# change leader key from 'C-b' to 'C-a'
set-option -g prefix C-a
bind-key C-a send-prefix

# split planes using | (horizontal) and - (vertical)
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Navigate panes using vim navs
bind-key k  select-pane -U
bind-key j  select-pane -D
bind-key h  select-pane -L
bind-key l  select-pane -R

# open new tabs with 't'
bind-key t new-window

# hot reload tmux config using '<leader> r'
bind r source-file ~/.tmux.conf

# Don't rename windows automatically
set-option -g allow-rename off

# Vim config when browsing window
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind P paste-buffer
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# Tmux plugins
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux2k'

# Theme
# use a theme
set -g @tmux2k-theme 'catppuccin'

# to show icons only
set -g @tmux2k-icons-only true

# to customize duo bg and fg
set -g @tmux2k-duo-fg "#1688f0" # this will get you duo blue shown above
set -g @tmux2k-duo-bg "#000000" # this will set the bg for duo theme

# to set powerline symbols
set -g @tmux2k-right-sep  # alternate right status bar sep
set -g @tmux2k-win-right-sep  # alternate window right sep

# to not show powerline
set -g @tmux2k-show-powerline false

# set start icon, accpets: `session`, 'window`, or any string
set -g @tmux2k-start-icon ""

# Theme plugins
# set the left and right plugin sections
set -g @tmux2k-left-plugins "git cpu ram"
set -g @tmux2k-right-plugins "battery network time"

# to enable compact window list size
set -g @tmux2k-compact-windows true

# weather scale
set -g @tmux2k-show-fahrenheit true 

# 24 hour time
set -g @tmux2k-military-time true

# network interface to watch
set -g @tmux2k-network-name "wlo1"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
